### PR TITLE
Update for Analysis Vignette

### PR DESCRIPTION
**Pull request by stevegbrooks**
1. Make prior specification more generic, 
	•	i.e. just add explanation text that prior can be based on historical data and that functions from RBesT can be used 
	•	specify non-informative priors for all dose groups

2. Specification of trial design
	•	Prepare dummy code for all possible dose-response models (linear, exp, emax, sigEmax, linlog, logistic, beta and quadratic)
	•	Include a visualization for the specified dose-response models 
	•	In addition show parameters for all models on the parameter scale, and assumed treatment effects for the specified dose groups (similar to MCPModPack2 app)

3. Combination of prior information and trial results
	•	Prepare a table showing the posterior results in a nice format
4. Execution of Bayesian MCPMod Test step
	•	Instead of performing all different contrast calculations, just showcase one and add text explaining the different options
	•	Prepare a nice table summarizing the BMCP test results
5. Model fitting
	•	Prepare and include nice visualizations of the model fits 
	•	Prepare a table listing all predictions 
	•	Prepare a table listing the bootstrap quantiles

### CODE REVIEW

**Comment by stevegbrooks** [comment]
linInt, betaMod, quadratic are not model shapes that are supported by the package yet, so we can't run `getModelFits` on those shapes. Should we adapt `getModelFits` function to allow for it?

**Comment by stevegbrooks** [comment]
## Feedback session on 1st draft of quarto vignette

### Dose-Response Models

1. Make dose response model specifications more closely follow how the "ShinyTool for Dose-Response Curve" interface presents things. Also make it more intelligible in the clinical context. Here we can provide a template for various model specifications without evaluation, and make the evaluated part of it more simple. 
2. Remove linInt model as its not really used in practice - add note about it for the reader.
3. Provide specifications on guesstimate scale and parameter scale (a la ShinyTool, mentioned above). 
4. Align presentation of model parameterization with the "Reports" section of ShinyTool.

### BMCP results

1. Adjust S3 method that prints the output object of `performBayesianMCP`: sign, crit_prob, and max_post_prob are summary values, then ess_avg, then present model shape info. There's a hierarchy to the info that should be captured by the print() method.

### Modeling

1. Update `getModelFits` to support betaMod model shape. 

### Github actions

1. @Xyarz to update the github actions to support quarto vignettes

**Comment by stevegbrooks** [comment]
# Feedback on 2nd draft

## Finish unfinished tasks from previous draft

- [ ]  Adjust S3 method that prints the output object of performBayesianMCP: sign, crit_prob, and max_post_prob are summary values, then ess_avg, then present model shape info. There's a hierarchy to the info that should be captured by the print() method.
- [ ]  Update predictModelFit to support betaMod model shape.
- [ ]  Allow predictModelFit to access scal param of model
- [ ] @Xyarz to update the github actions to support quarto vignettes

## General

- [ ] Make it less wordy and/or pedantic
- [ ] Use consistent rounding to 3 decimal places throughout

**Comment by stevegbrooks** [comment]
# Feedback on 3rd draft

## BayesianMCPMod team

- [ ] @sebastianbossert debug nloptr when model == 'betaMod' (crazy predictions!)

## Code Review end of May

- [ ] @Xyarz @stevegbrooks 

Then, it should be ready to go.

## Potential future work:

- App
- Simulation vignette

**Review by Xyarz — APPROVED** [review]

**Pull request merged**
